[package]
name = "xtask"
description = "Auxiliary build tool"
version = "0.5.2"
edition = { workspace = true }
publish = false

[dependencies]
anyhow = "1.0"
xflags = "0.3"
xshell = "0.2"

[lints]
workspace = true
